version: '3'

networks:
  packt-api:

services:
  site:
    image: nginx:stable-alpine
    container_name: packt-api-nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
    networks:
      - packt-api

  db:
    image: postgres:11
    container_name: packt-api-db
    restart: unless-stopped
    ports:
      - 5432:5432/tcp
    environment:
      POSTGRES_USER: packt-api
      POSTGRES_PASSWORD: packt-api
      POSTGRES_DB: packt-api
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    networks:
      - packt-api

    
  php:
    build:
      context: ./php-app/
      dockerfile: Dockerfile
    container_name: packt-api-php
    volumes:
      - ./src:/var/www/html
      - ./php-app:/var/www/html/php-app
    ports:
      - "9000:9000"
    networks:
      - packt-api
  
  npm:
    image: node:latest
    container_name: npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: [ 'npm' ]

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    environment:
      MH_UI_WEB_PATH: _/mail
    ports: 
      - 1025:1025 # smtp server
      - 8025:8025 # web ui 
    networks:
      - packt-api

  logdna:
    environment:
      - LOGDNA_KEY=b55aa968c116697edc160b46b0af8d2e
    image: logdna/logspout:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock